# Generated by Django 5.1.2 on 2024-10-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('create_date', models.DateField()),
                ('author', models.CharField(max_length=40)),
                ('like_count', models.IntegerField()),
                ('published', models.BooleanField()),
            ],
        ),
    ]
